### ISSUE TITLE
Uncaught runtime errors:

### ISSUE THREAD

**Issue by itsalwaysamir** [MatKollar/Invoice_OCR_app#12]
Hi,
many thanks for your project!
i got the error below after running the container.

![image](https://github.com/MatKollar/Invoice_OCR_app/assets/110420666/de378958-a8d1-4b49-a729-1ce78c7c104f)

**Comment by MatKollar** [comment]
Hi, thank you for reporting the issue.

Can you please provide more info, how you encountered with the error ?
I cannot replicate the situation when error shows up.

You can't even log in because of an error?

**Comment by itsalwaysamir** [comment]
Hi,
yes, when i want to log in. i see the error.. all process before seemed ok

**Comment by MatKollar** [comment]
The problem you have encountered is probably similar to this one [#11 Error on login](https://github.com/MatKollar/Invoice_OCR_app/issues/11).

Please check if you have flask-session==0.5.0 in requirements.txt, if no pull the newer version and rebuild your backend container by using `docker compose build backend` command.

**Comment by muditjaju** [comment]
Hello @MatKollar - My requirements.txt file contains flas-session==0.50 but the login error still remains
<img width="477" alt="Screenshot 2024-04-06 at 10 31 28 AM" src="https://github.com/MatKollar/Invoice_OCR_app/assets/3458204/d3f38b04-3676-4479-a370-de633b1c839a">
<img width="808" alt="Screenshot 2024-04-06 at 10 31 35 AM" src="https://github.com/MatKollar/Invoice_OCR_app/assets/3458204/2eeefbe1-256b-4b53-a02e-a1ff5c84d50e">

**Comment by MatKollar** [comment]
Hello @muditjaju, make sure your backend is running properly. You can check the logs in the backend container.

I have added additional error handling to prevent runtime errors when backend server is not reachable.
