### ISSUE TITLE
Uncaught runtime errors: #12

### ISSUE THREAD

**Issue by borisovalex** [MatKollar/Invoice_OCR_app#30]
I have the same issue as #12 
The problem is that I run app on another computer, but all posts in fronted are hardcoded with localhost:5000
LoginPage.js
...
try {
      await httpRequest.post("http://localhost:5000/login", {
        email,
        password,
      });
      
, so  frontend never reaches backend,
It would be great if backend host is configurable,

**Comment by MatKollar** [comment]
Hello @borisovalex, thank you for mentioning this issue.

You can now configure your backend host in the [.env](https://github.com/MatKollar/Invoice_OCR_app/blob/master/frontend/.env) file located in the frontend directory.
